### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by kanishk-reply** [Ki-Reply-Uk/xchange24-FE#4]
add a new button next to the start now button

**Comment by kicodedev2** [comment]
User Story:
As a website user, I want a new button added next to the "Start Now" button, so that I can access additional functionalities easily and directly from the main page.

If the user story is to your standards, type 'Yes'. Otherwise, give amendments to the user story.

**Comment by kanishk-reply** [comment]
yes

**Comment by kicodedev2** [comment]
User story acknowledged. Code fix agent executing fix based on this user story...
